// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjwdezetgwedsusqpiqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdqd2RlemV0Z3dlZHN1c3FwaXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzM0NTksImV4cCI6MjA2NjAwOTQ1OX0.v3OaF48MB9A7H0lWMjUju3tCXaXOUi175Q4oAhVS-EU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});